config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  resources :courses, only: [:index, :show] do
    resources :progresses, only: [:create]
  end
  resources :quizzes, only: [:index]
  resources :questions, only: [:show,] do
    resources :answers, only: [:create,:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :family
  has_many :progresses, dependent: :destroy
  has_one_attached :photo

end

app/models/family.rb
class Family < ApplicationRecord

  has_many :courses, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_one_attached :photo

end

app/models/progress.rb
class Progress < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :family
  has_many :answers, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :progresses, dependent: :destroy
  has_many :answers, dependent: :destroy
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.question = @question
    @answer.user = current_user
    if @answer.user_answer == @question.correct_answer
      @answer.status = true
    else
      @answer.status = false
    end
    @answer.save!
    @quizz = @question.family
    @quizz_questions = @quizz.questions
    @un_answers_questions = []
    @bad_answers = []

    @quizz_questions.each do |quizz_question|
      if quizz_question.answers.empty?
        @un_answers_questions << quizz_question
      elsif quizz_question.answers[0].status == false
        @bad_answers << quizz_question
      end
    end

    if !@un_answers_questions.empty?
      redirect_to question_path(@un_answers_questions.sample)
    elsif !@bad_answers.empty?
      redirect_to question_path(@bad_answers.sample)
    else
      redirect_to question_path(@quizz_questions.sample)
    end
  end

  def update
    @answer = Answer.find(params[:id])
    @new_answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer.user_answer = @new_answer.user_answer
    if @answer.user_answer == @question.correct_answer
      @answer.status = true
    else
      @answer.status = false
    end
    @answer.save!
    @quizz = @question.family
    @quizz_questions = @quizz.questions
    @un_answers_questions = []
    @bad_answers = []

    @quizz_questions.each do |quizz_question|
      if quizz_question.answers.empty?
        @un_answers_questions << quizz_question
      elsif quizz_question.answers[0].status == false
        @bad_answers << quizz_question
      end
    end

    if !@un_answers_questions.empty?
      redirect_to question_path(@un_answers_questions.sample)
    elsif !@bad_answers.empty?
      redirect_to question_path(@bad_answers.sample)
    else
      redirect_to question_path(@quizz_questions.sample)
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:user_answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  def default_url_options
  { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all

      @courses = @courses.where("duration <= ?", params[:duration])  if params[:duration].present?

      @courses = @courses.joins(:family).where("families.name = ?", params[:family]) if params[:family].present?
      @courses = @courses.where(" difficulty = ?", params[:difficulty]) if params[:difficulty].present?

    @courses = @courses.reverse
    @families = Family.all
  end

  def show
    @course = Course.find(params[:id])
    @user = current_user
    @progress = Progress.find_by(course: @course, user: @user )
    @family = Family.find_by(courses: @course)
    courses = Course.where(family: @family)
    courses.each_with_index do |course, index|
      if course.id == @course.id
        @next_course = courses[index + 1]
        @prev_course = courses[index - 1]
        if index.zero?
          @prev_course = nil
        end
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @quizzes = Family.all
    @courses = Course.all
    @perfect = @courses.count + @quizzes.count
    @courses_done = current_user.progresses
  end
end

app/controllers/progresses_controller.rb
class ProgressesController < ApplicationController
  def create
    @course = Course.find(params[:course_id])
    @user = current_user
    @progress = Progress.new(completed: true)
    @progress.course = @course
    @progress.user = @user
    @progress.save!
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:id])
    @user = current_user
    @user_answers = @user.answers
    @user_answers.each do |user_answer|
      if user_answer.question == @question
        @status = true
        @user_answer = user_answer
      end
    end

    @quizz = @question.family
    @quizz_questions = @quizz.questions
    @un_answers_questions = []
    @bad_answers = []
    @good_answers = []
    @quizz_questions.each do |quizz_question|
      if quizz_question.answers.empty?
        @un_answers_questions << quizz_question
      elsif quizz_question.answers[0].status == false
        @bad_answers << quizz_question
      else
        @good_answers << quizz_question
      end
    end
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def index
    @quizzes = Family.all
    @next_question = nil
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/courses/_form_duration.html.erb
<div class="filtre-text">
  Les cours sur le
    <button class="btn dropdown-toggle filter" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
      <% if params[:family].present? %>
           <%= params[:family] %>
        <% else %>
          <%= "Choisissez un rayon" %>
          <% end %>
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <% @families.each do |family| %>
      <%= link_to "#{family.name}",courses_path(family: family.name, difficulty: params[:difficulty], duration: params[:duration]), class: "dropdown-item" %>
    <% end %>
    </div>
</div>

<div class="difficulties">
  <div>
    <div class="dropdown-filter">
      <span class="filtre-text">Votre niveau</span>
      <button class="btn dropdown-toggle filter" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
        <% if params[:difficulty].present? %>
           <%= params[:difficulty] %>
        <% else %>
          <%= "Tous" %>
          <% end %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to "Débutant",courses_path(difficulty: "Débutant", family: params[:family], duration: params[:duration]), class: "dropdown-item"%>
        <%= link_to "Intermédiaire",courses_path(difficulty: "Intermédiaire", family: params[:family], duration: params[:duration]), class: "dropdown-item" %>
        <%= link_to "Difficile",courses_path(difficulty: "Difficile", family: params[:family], duration: params[:duration]), class: "dropdown-item" %>
      </div>
    </div>
  </div>

  <div>
    <div class="dropdown-filter">
    <span class="filtre-text">Choisissez votre durée</span>
      <button class="btn dropdown-toggle filter" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false">
        <% if params[:duration].present? %>
           <%= params[:duration] %>
        <% else %>
          <%= "Tous" %>
          <% end %>
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <%= link_to "30 min",courses_path(duration: 30, family: params[:family], difficulty: params[:difficulty]), class: "dropdown-item" %>
        <%= link_to "45 min",courses_path(duration: 45, family: params[:family], difficulty: params[:difficulty]), class: "dropdown-item" %>
        <%= link_to "90 min",courses_path(duration: 90, family: params[:family], difficulty: params[:difficulty]), class: "dropdown-item" %>
      </div>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<div class="filter">
  <%# <div class="filtrer">
    <h2 class="filtre-text">Filtrer vos cours</h2>
    <h3 class="btn-filtre" id="tous">Tous</h3>
    <h3 class="btn-filtre" id="en-cours">En cours </h3>
    <h3 class="btn-filtre" id="termines">Terminés</h3>
  </div> %>
  <%= render 'form_duration' %>
</div>




<div class="cards">
  <% @courses.each do |course| %>
    <div class = "card-product">
      <% unless course.progresses.empty? %>
        <i class="fas fa-check-circle"></i>
      <% else %>
        <i class="fas fa-check-circle hidden"></i>
      <% end %>
        <%= cl_image_tag course.photo.key, height: 300, width: 400, crop: :fill %>
        <div class="card-product-infos">
          <h2><%= course.title %></h2>
          <ul class= "card-online">
            <li>
              <div class = "alignement m-3">
                <% if course.difficulty == "Difficile" %>
                    <i class="fas fa-hammer hard"></i> <i class="fas fa-hammer hard"></i> <i class="fas fa-hammer hard"></i>
                <% elsif course.difficulty == "Intermédiaire" %>
                    <i class="fas fa-hammer medium"></i> <i class="fas fa-hammer medium"></i></i> <i class="fas fa-hammer inactive"></i>
                <% else %>
                    <i class="fas fa-hammer easy"></i> <i class="fas fa-hammer inactive"></i> <i class="fas fa-hammer inactive"></i>
                <% end %>
                <p>Difficulté</p>
              </div>
            </li>
            <li>
              <div class = "alignement m-3 text-center">
                <i class="far fa-clock"></i>
                <p id="style", style="margin: 8px"> <%= course.duration %> min</p>
              </div>
            </li>
          </ul>
          <%= link_to 'DÉMARRER', course_path(course), class: "btn-cours" %>
        </div>
      </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet">

  </head>

  <body <% if current_page?(root_path)%> class="container_homepage" <% end %>>

    <% if current_page?(root_path) %>

      <%= yield %>

    <% else %>

      <%= render 'shared/navbar' %>

      <div class="custom-container">

        <%= yield %>

      </div>

      <%= render 'shared/footer' %>

    <% end %>


    <%= render 'shared/flashes' %>


  </body>

</html>

app/views/pages/dashboard.html.erb
<h2 class="header1">Toutes mes statistiques</h2>
<div>

  <div class="swiper mySwiperFree">

    <div class="swiper-wrapper">

      <div class="swiper-slide swiper-free">
        <div class="stat">
          <div class="d-flex justify-content-between">

            <h1><%= @courses_done.count %></h1>
            <div role="progressbar" aria-valuenow="<%= ((@courses_done.count / @courses.count.to_f) * 100).round %>" aria-valuemin="0" aria-valuemax="100" style="--value: <%= ((@courses_done.count / @courses.count.to_f) * 100).round %>"></div>

          </div>

          <h2>Cours terminés</h2>

        </div>
      </div>

      <div class="swiper-slide swiper-free">
        <div class="stat">
          <div class="d-flex justify-content-between">
            <h1><% counter_quizz = @quizzes.count %>
              <% @quizzes.each do |quizz| %>
                <% counter_questions = quizz.questions.count %>
                <% quizz.questions.each do |question| %>
                  <% if question.answers.empty? || question.answers[0].status == false %>
                    <% counter_questions -= 1 %>
                  <% end %>
                <% end %>
                <% if counter_questions != quizz.questions.count %>
                  <% counter_quizz -= 1 %>
                <% end %>
              <% end %>
              <%= counter_quizz %></h1>

            <div role="progressbar" aria-valuenow="<%= ((counter_quizz / @quizzes.count.to_f) * 100).round %>" aria-valuemin="0" aria-valuemax="100" style="--value: <%= ((counter_quizz / @quizzes.count.to_f) * 100).round %>"></div>
          </div>
            <h2>Quizz Terminés</h2>
        </div>
      </div>

      <div class="swiper-slide swiper-free">
        <div class="stat">
            <h1><%= (((counter_quizz / @quizzes.count.to_f) * 50).round) + ((@courses_done.count / @courses.count.to_f) * 50).round %>%</h1>
          <h2>Progression Globale</h2>
        </div>
      </div>

      <%# <div class="swiper-slide swiper-free">
        <div class="stat">
          <div class="d-flex justify-content-between">
            <h1>2</h1>
            <div role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100" style="--value: 100"></div>
          </div>
          <h2>Heures passés à travailer ! </h2>
        </div>
      </div> %>

      <%# <div class="swiper-slide swiper-free">
        <div class="stat">
          <div class="d-flex justify-content-between">
            <h1>17</h1>
            <div role="progressbar" aria-valuenow="88" aria-valuemin="0" aria-valuemax="100" style="--value: 88"></div>
          </div>
          <h2>Bonnes réponses aux quizz</h2>
        </div>
      </div> %>

    </div>

    <div class="swiper-pagination"></div>
  </div>

  <%# <% if !@courses_done.empty? %>
    <%# <% last_course_done = @courses_done.last %>
    <%# <% @next_course = Course.find_by_id(last_course_done.course.id + 1) %>
    <%# <% if !@next_course.nil? %>

    <div class="dernier-cours"><h2 class="header2">Dernier cours étudié</h2></div>
      <div class="last-lesson">
        <img src="https://www.mesdepanneurs.fr/sites/mesdepanneurs.fr/files/field/image/pose-de-carrelage.jpg" />

        <div class="info">
          <div class="info-cours">
            <h2 style="font-size: 30px;">Les revêtements de sol extérieur</h2>
          </div>
            <div>
              <h3><%= link_to "REPRENDRE", courses_path, class:"btnreprendre" %></h3>
            </div>
        </div>
      </div>
    <%# <% end %>
  <%# <% end %>
  </div>



  <div class="carousel-cours"><h2 class="header3">Etudiez vos gammes dans différents secteurs</h2></div>
  <div class="swiper mySwiper" style= "height: 500px;">
    <div class="swiper-wrapper">
    <% @quizzes.each do |family| %>
      <div class="swiper-slide">
        <%= link_to courses_path(family: "#{family.name}")  do %>
        <%= cl_image_tag family.photo.key %>
        <div class="contenu-slide-swiper", style="padding: 20px;">
          <div class="contenu-relatif">

            <h2><%= family.name %></h2>
            <% @family_courses = family.courses %>
              <% @done_course = [] %>
              <% @family_courses.each do |family_course| %>
                <% if family_course.progresses.empty? %>
                <% elsif family_course.progresses[0].completed == true %>
                  <% @done_course << family_course %>
                <% end %>
              <% end %>


            <div class="progress-container-quizz-version-carousel">
              <div class="progress-bar-full" style ="width: 75%">
                <div class="master-progress" style="width: 0%", data-good="<%= @done_course.count %>", data-all="<%= @family_courses.count %>" ></div>
              </div>
            </div>
            <div class="percent-calcul">
              <p><%= ((@done_course.count.to_f / @family_courses.count) * 100).round %> %</p>
            </div>
          </div>


        </div>
      </div>
      <% end %>
    <% end %>
    </div>
    <div class="swiper-pagination"></div>
    <%# <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div> %>
  </div>

  <div class="text-nouveauté"><h2 class="header4">Travailler vos nouveaux cours</h2></div>
  <div class = "nv">
    <img src="https://m1.lmcdn.fr/media/15/5d8b63971a8f316b60ed9e8a/1753024969/cours-de-bricolage-en-magasin5d8b639697844600099b8346.jpg?width=800&crop=16:9,smart" >
    <div class= "st">
      <div class = "st-nouveau">
        <h2>RETROUVEZ NOS NOUVEAUX COURS</h2>
      </div>
      <div>
      <h3 class = "btndecouvrir"> <%= link_to "Découvrir",courses_path %></h3>
      </div>
    </div>
  </div>

</div>

app/views/pages/home.html.erb
<div class="container_homepage">

  <div class="custom-shape-divider-top-1638785480">
      <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none">
          <path d="M892.25 114.72L0 0 0 120 1200 120 1200 0 892.25 114.72z" class="shape-fill"></path>
      </svg>
  </div>


  <div class="entreprise">
    <h1>SKALLUP</h1>
    <p>Perfectionnez-vous en ligne sur votre métier.</p>
  </div>

  <div class="button_commencer">
    <%= link_to "Commencer", dashboard_path %>
  </div>


  <div class="presentation">
    <div class="text">
      <i class="fas fa-graduation-cap"></i>
      <h2>Une formation complète</h2>
      <p>Découvrez plus de 200 cours sur vos produits.</p>
    </div>

    <div class="text">
      <i class="fas fa-chalkboard-teacher"></i>
      <h2>Un accès illimité</h2>
      <p>Une formation en ligne accessible n'importe où, à n'importe quelle heure.</p>
    </div>

    <div class="text">
      <i class="fas fa-check"></i>
      <h2>Devenir un expert</h2>
      <p>Devenez plus efficace dans votre discours de vente et boostez vos ventes.</p>
    </div>

  </div>

</div>

app/views/questions/show.html.erb
<div class="button-back">
  <%= link_to "RETOUR AUX QUIZZ", quizzes_path %>
</div>

<div class="progress-container">
  <h2 id= "ajust"> <%= @good_answers.count %> / <%= @quizz_questions.count %> questions </h2>
  <div class="progress-bar-full quizzprogress">
    <div class="master-progress" style="width: 0%", data-good="<%= @good_answers.count %>", data-bad="<%= @bad_answers.count %>", data-all="<%= @quizz_questions.count %>" ></div>
    <div class="not-master-progress" style="width: 0%"></div>
  </div>
</div>

<% if ((@good_answers.count.to_f / @quizz_questions.count) * 100).round == 100 %>
  <div class="question-cards done">
<% else %>
  <div class="question-cards">
<% end %>

  <h2>Vrai ou Faux ?</h2>
  <h1><%= @question.content %></h1>
  <div class="question-answer">
    <% if @status == true %>
      <%= link_to "VRAI", question_answer_path(@question, @user_answer, answer: {user_answer: true}), method: :patch, class: "button-filter-v", remote: true %>
      <%= link_to "FAUX", question_answer_path(@question, @user_answer, answer: {user_answer: false}), method: :patch, class: "button-filter-r", remote: true %>
    <% else %>
      <%= link_to "VRAI", question_answers_path(@question, answer: {user_answer: true}), method: :post, class: "button-filter-v", remote: true %>
      <%= link_to "FAUX", question_answers_path(@question, answer: {user_answer: false}), method: :post, class: "button-filter-r", remote: true %>
    <% end %>
  </div>
</div>

app/views/quizzes/index.html.erb
<h1>Testez vous</h1>
<% @quizzes.each do |quiz| %>
  <% @quizz_questions = quiz.questions %>
  <% @good_answers = [] %>
  <% @quizz_questions.each do |quizz_question| %>
    <% if quizz_question.answers.empty? %>
    <% elsif quizz_question.answers[0].status == true %>
      <% @good_answers << quizz_question %>
    <% end %>
  <% end %>
  <% if ((@good_answers.count.to_f / @quizz_questions.count) * 100).round == 100 %>
    <div class="quizz-cards-index done">
  <% else %>
    <div class="quizz-cards-index">
  <% end %>
    <div class="progress-container-quizz">
      <div class="progress-bar-full" style ="width: 25%">
        <div class="master-progress" style="width: 0%", data-good="<%= @good_answers.count %>", data-all="<%= @quizz_questions.count %>" ></div>
      </div>
      <p><%= ((@good_answers.count.to_f / @quizz_questions.count) * 100).round  %>%</p>
  </div>

    <div class="quizz-cards-content">
      <h3>Quizz</h3>
      <h2><%= quiz.name  %></h2>
    </div>
    <div class="start-button">
      <% questions = quiz.questions %>
      <% bad_questions = [] %>
      <% un_answers_questions = [] %>
      <% questions.each do |question| %>
        <% if question.answers.empty? %>
          <% un_answers_questions << question %>
        <% elsif question.answers[0].status == false %>
          <% bad_questions << question %>
        <% end %>
      <% end %>
      <% if !un_answers_questions.empty? %>
        <% @next_question = un_answers_questions.sample %>
      <% elsif !bad_questions.empty?%>
        <% @next_question = bad_questions.sample %>
      <% else %>
        <% @next_question = questions.sample %>
      <% end %>
      <%= link_to "DEMARRER", question_path(@next_question) %>
    </div>
  </div>
<% end %>


<script>
  const all_questions = <%= @quizz_questions.count %>
  const good_questions = <%= @good_answers.count %>
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
      <a href="#"><i class="fab fa-app-store-ios"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">

  <div class="main-navbar">
    <div class="research-bar">
      <h2 class="skallup"><%= link_to "SKALLUP", dashboard_path %></h2>
      <div class="titre">
        <% if !current_user.nil? %>
          <h2>Welcome <%= current_user.username %> !</h2>
        <% end %>
        <p>Devenez un expert du bricolage facilement et rapidement</p>
      </div>
      <div class="search-bar">
        <form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
          <div class="search-form-control form-group">
            <i class="far fa-bell"></i><input class="form-control string required" type="text" placeholder="Rechercher une leçon, un cours..." name="search[query]" id="search_query" />
          </div>
        </form>
      </div>
    </div>
  </div>


  <% if current_user.nil? %>
    <div class="nav-unroll">
      <%= link_to "LOGIN", new_user_session_path, class: "link-nav-unroll" %>
    </div>
  <% else %>
    <div class="navbar-link">
        <div class="user">
          <img src="https://avatars.githubusercontent.com/u/90854439?v=4" alt="photo">
          <p class="username"><%= current_user.username %></p>
        </div>
      <ul class="link">
        <div class="link-nav">
          <li><%= link_to "Dashboard", dashboard_path %></li>
          <li><%= link_to "Mes cours", courses_path %></li>
          <li id= "espace"><%= link_to "Quizz", quizzes_path %></li>
          <%= link_to "LOG-OUT", destroy_user_session_path, method: :delete, class: "logout-link-nav"%>
        </div>
      </ul>
    </div>
  <% end %>
</div>